/**
 * [컴포넌트 갤러리 쇼케이스]
 * - 100% SEED CLI 컴포넌트 (`npx @seed-design/cli add ui:*`) 기반
 * - 100% SEED Design System 시맨틱 CSS 토큰 (`var(--seed-*)`) 적용
 */

import { useState, useRef, useEffect } from 'react';
import {
  IconDeliveryRegular,
  IconAddRegular,
  IconChevronRightRegular,
  IconHeartRegular,
} from "@seed-design/icon";

// Import CLI React UI components generated by npx @seed-design/cli add ui:*
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '../components/ui/accordion';
import { ActionButton, PrefixIcon, SuffixIcon, Icon } from '../components/ui/action-button';
import { Avatar, AvatarBadge, AvatarStack } from '../components/ui/avatar';
import { AttachmentField, AttachmentInput, AttachmentDropzone } from '../components/ui/attachment-field';
import {
  AlertDialogRoot,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogAction,
} from '../components/ui/alert-dialog';

// Alert Dialog Layout Variants
const ALERT_DIALOG_LAYOUTS = [
  {
    key: 'single', label: 'Single',
    title: 'Title은 작성을 권장해요', desc: '본문 내용을 입력해주세요.',
    kind: 'pair', buttons: [{ variant: 'neutralSolid', label: '라벨' }],
  },
  {
    key: 'neutral', label: 'Neutral',
    title: 'Title은 작성을 권장해요', desc: '본문 내용을 입력해주세요.',
    kind: 'pair', buttons: [{ variant: 'neutralWeak', label: '라벨' }, { variant: 'neutralSolid', label: '라벨' }],
  },
  {
    key: 'neutralOverflow', label: 'Neutral (Overflow)',
    title: 'Title은 작성을 권장해요', desc: '본문 내용을 입력해주세요.',
    kind: 'pair', buttons: [{ variant: 'neutralWeak', label: '취소할래요' }, { variant: 'neutralSolid', label: '네 확인했어요 진행할게요' }],
  },
  {
    key: 'critical', label: 'Critical',
    title: '삭제하시겠어요?', desc: '삭제한 게시글은 복구할 수 없어요.',
    kind: 'pair', buttons: [{ variant: 'neutralWeak', label: '취소' }, { variant: 'criticalSolid', label: '삭제' }],
  },
  {
    key: 'criticalOverflow', label: 'Critical (Overflow)',
    title: '삭제하시겠어요?', desc: '삭제한 게시글은 복구할 수 없어요.',
    kind: 'pair', buttons: [{ variant: 'neutralWeak', label: '취소할래요' }, { variant: 'criticalSolid', label: '네 삭제할게요 진행할게요' }],
  },
  {
    key: 'nonePreferred', label: 'NonePreferred',
    title: 'Title은 작성을 권장해요', desc: '본문 내용을 입력해주세요.',
    kind: 'stack', buttons: [{ variant: 'neutralSolid', label: '라벨' }, { variant: 'ghost', label: '라벨', muted: true }],
  },
];

function AlertDialogDemo() {
  const [selectedLayoutKey, setSelectedLayoutKey] = useState('single');
  const layout = ALERT_DIALOG_LAYOUTS.find((l) => l.key === selectedLayoutKey) || ALERT_DIALOG_LAYOUTS[0];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x4)', width: '100%', maxWidth: 360, margin: '0 auto' }}>
      {/* Layout Variant Selector Tabs */}
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--seed-dimension-x1_5)', justifyContent: 'center' }}>
        {ALERT_DIALOG_LAYOUTS.map((l) => (
          <button
            key={l.key}
            type="button"
            className={`comp-nav-btn${l.key === selectedLayoutKey ? ' active' : ''}`}
            onClick={() => setSelectedLayoutKey(l.key)}
            style={{ fontSize: 'var(--seed-font-size-t2)', paddingInline: 'var(--seed-dimension-x2)', paddingBlock: 'var(--seed-dimension-x1)' }}
          >
            {l.label}
          </button>
        ))}
      </div>

      {/* Selected Layout Dialog Card */}
      <div style={{ position: 'relative', width: '100%' }}>
        <AlertDialogRoot open={true}>
          <AlertDialogContent style={{ width: '100%', position: 'relative', transform: 'none' }}>
            <AlertDialogHeader>
              <AlertDialogTitle>{layout.title}</AlertDialogTitle>
              {layout.desc && <AlertDialogDescription>{layout.desc}</AlertDialogDescription>}
            </AlertDialogHeader>
            <AlertDialogFooter>
              {layout.kind === 'stack' ? (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2)', alignItems: 'stretch', width: '100%' }}>
                  {layout.buttons.map((b, i) => (
                    <AlertDialogAction
                      key={i}
                      variant={b.variant}
                      size="medium"
                      style={b.muted ? { color: 'var(--seed-color-fg-neutral-muted)', fontWeight: 'var(--seed-font-weight-bold)' } : undefined}
                    >
                      {b.label}
                    </AlertDialogAction>
                  ))}
                </div>
              ) : (
                <div style={{ display: 'flex', flexWrap: 'wrap-reverse', gap: 'var(--seed-dimension-x2)', width: '100%' }}>
                  {layout.buttons.map((b, i) => (
                    <AlertDialogAction
                      key={i}
                      variant={b.variant}
                      size="medium"
                      style={{
                        flexGrow: 1,
                        minWidth: `calc(${100 / layout.buttons.length}% - var(--seed-dimension-x2) / ${layout.buttons.length})`,
                      }}
                    >
                      {b.label}
                    </AlertDialogAction>
                  ))}
                </div>
              )}
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialogRoot>
      </div>
    </div>
  );
}

function IdentityPlaceholderSVG({ size = 48, identity = "person" }) {
  return (
    <svg width={size} height={size} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" style={{ width: '100%', height: '100%' }}>
      <rect width="48" height="48" rx="24" fill="var(--seed-color-bg-neutral-weak)" />
      {identity === "person" ? (
        <path d="M24 14C20.6863 14 18 16.6863 18 20C18 23.3137 20.6863 26 24 26C27.3137 26 30 23.3137 30 20C30 16.6863 27.3137 14 24 14ZM14 34C14 29.5817 18.4772 26 24 26C29.5228 26 34 29.5817 34 34V35H14V34Z" fill="var(--seed-color-fg-neutral-muted)" />
      ) : (
        <path d="M16 16H32V34H16V16ZM20 20H24V24H20V20ZM20 26H24V30H20V26ZM26 20H28V24H26V20ZM26 26H28V30H26V26Z" fill="var(--seed-color-fg-neutral-muted)" />
      )}
    </svg>
  );
}

function AvatarDemo() {
  const sampleImg = "https://avatars.githubusercontent.com/u/54893898?v=4";

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x7)', width: '100%', alignItems: 'center' }}>
      {/* 1. Sizes */}
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Sizes (24px ~ 96px)
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--seed-dimension-x3)', alignItems: 'center', justifyContent: 'center' }}>
          {['24', '36', '48', '64', '80', '96'].map((sz) => (
            <div key={sz} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x1)' }}>
              <Avatar size={sz} src={sampleImg} alt={`Avatar ${sz}`} />
              <span style={{ fontSize: 'var(--seed-font-size-t2)', color: 'var(--seed-color-fg-neutral-muted)' }}>{sz}px</span>
            </div>
          ))}
        </div>
      </div>

      {/* 2. Badge & Mask */}
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Badge & Mask (Circle, Flower, Shield)
        </div>
        <div style={{ display: 'flex', gap: 'var(--seed-dimension-x5)', alignItems: 'center', justifyContent: 'center' }}>
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x1_5)' }}>
            <Avatar size="64" badgeMask="circle" src={sampleImg} alt="Avatar">
              <AvatarBadge>
                <div style={{ width: '100%', height: '100%', borderRadius: '50%', backgroundColor: 'var(--seed-color-palette-green-600)' }} />
              </AvatarBadge>
            </Avatar>
            <span style={{ fontSize: 'var(--seed-font-size-t3)', color: 'var(--seed-color-fg-neutral-subtle)' }}>Circle Badge</span>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x1_5)' }}>
            <Avatar size="64" badgeMask="flower" src={sampleImg} alt="Avatar">
              <AvatarBadge>
                <svg width="100%" height="100%" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M12 2C10.9 2 9.9 2.6 9.4 3.5C8.4 3.1 7.2 3.4 6.5 4.2C5.8 5 5.5 6.2 5.9 7.2C5 7.7 4.4 8.7 4.4 9.8C4.4 10.9 5 11.9 5.9 12.4C5.5 13.4 5.8 14.6 6.5 15.4C7.2 16.2 8.4 16.5 9.4 16.1C9.9 17 10.9 17.6 12 17.6C13.1 17.6 14.1 17 14.6 16.1C15.6 16.5 16.8 16.2 17.5 15.4C18.2 14.6 18.5 13.4 18.1 12.4C19 11.9 19.6 10.9 19.6 9.8C19.6 8.7 19 7.7 18.1 7.2C18.5 6.2 18.2 5 17.5 4.2C16.8 3.4 15.6 3.1 14.6 3.5C14.1 2.6 13.1 2 12 2Z" fill="var(--seed-color-palette-green-600)" />
                  <path d="M9.5 9.8L11 11.3L14.5 7.8" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </AvatarBadge>
            </Avatar>
            <span style={{ fontSize: 'var(--seed-font-size-t3)', color: 'var(--seed-color-fg-neutral-subtle)' }}>Flower Badge</span>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x1_5)' }}>
            <Avatar size="64" badgeMask="shield" src={sampleImg} alt="Avatar">
              <AvatarBadge>
                <svg width="100%" height="100%" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M12 2L4 5V11C4 16.5 7.4 21.6 12 23C16.6 21.6 20 16.5 20 11V5L12 2Z" fill="var(--seed-color-palette-blue-600)" />
                  <path d="M9.5 11.5L11 13L14.5 9.5" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </AvatarBadge>
            </Avatar>
            <span style={{ fontSize: 'var(--seed-font-size-t3)', color: 'var(--seed-color-fg-neutral-subtle)' }}>Shield Badge</span>
          </div>
        </div>
      </div>

      {/* 3. Avatar Stack */}
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Avatar Stack
        </div>
        <AvatarStack size="48">
          {[0, 1, 2, 3].map((idx) => (
            <Avatar key={idx} size="48" src={sampleImg} alt={`User ${idx}`} />
          ))}
        </AvatarStack>
      </div>

      {/* 4. Fallback */}
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Fallback Placeholders
        </div>
        <div style={{ display: 'flex', gap: 'var(--seed-dimension-x5)', alignItems: 'center', justifyContent: 'center' }}>
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x1_5)' }}>
            <Avatar size="64" fallback={<IdentityPlaceholderSVG size={64} identity="person" />} />
            <span style={{ fontSize: 'var(--seed-font-size-t3)', color: 'var(--seed-color-fg-neutral-subtle)' }}>Person</span>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x1_5)' }}>
            <Avatar size="64" fallback={<IdentityPlaceholderSVG size={64} identity="business" />} />
            <span style={{ fontSize: 'var(--seed-font-size-t3)', color: 'var(--seed-color-fg-neutral-subtle)' }}>Business</span>
          </div>
        </div>
      </div>
    </div>
  );
}

function AccordionDemo() {
  const renderContent = (text) => (
    <div
      style={{
        paddingInline: 'var(--seed-dimension-spacing-x-global-gutter)',
        paddingTop: 'var(--seed-dimension-x2)',
        paddingBottom: 'var(--seed-dimension-x3)',
        fontSize: 'var(--seed-font-size-t4)',
        lineHeight: 'var(--seed-line-height-t4)',
        color: 'var(--seed-color-fg-neutral-subtle)',
      }}
    >
      {text}
    </div>
  );

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x6)', width: '100%', maxWidth: 360, margin: '0 auto' }}>
      {/* 1. Inline Variant */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2)' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Variant: Inline
        </div>
        <Accordion defaultValue={["1"]} variant="inline" style={{ width: '100%' }}>
          <AccordionItem value="0">
            <AccordionTrigger title="배송 방법 안내" prefix={<IconDeliveryRegular style={{ width: 20, height: 20 }} />} />
            <AccordionContent>{renderContent("기본 배송은 당일 발송되며 1~2일 내에 안전하게 도착해요.")}</AccordionContent>
          </AccordionItem>
          <AccordionItem value="1">
            <AccordionTrigger title="반품/교환은 어떻게 하나요?" description="구매 후 7일 이내 신청" prefix={<IconDeliveryRegular style={{ width: 20, height: 20 }} />} />
            <AccordionContent>{renderContent("상품 상세페이지의 [반품/교환 신청] 버튼을 눌러 접수해주세요.")}</AccordionContent>
          </AccordionItem>
          <AccordionItem value="2" disabled>
            <AccordionTrigger title="고객센터 문의하기" prefix={<IconDeliveryRegular style={{ width: 20, height: 20 }} />} />
            <AccordionContent>{renderContent("운영시간은 평일 09:00 ~ 18:00 입니다.")}</AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>

      {/* 2. Separated Variant */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2)' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Variant: Separated
        </div>
        <Accordion defaultValue={["1"]} variant="separated" style={{ width: '100%' }}>
          <AccordionItem value="0">
            <AccordionTrigger title="배송 방법 안내" prefix={<IconDeliveryRegular style={{ width: 20, height: 20 }} />} />
            <AccordionContent>{renderContent("기본 배송은 당일 발송되며 1~2일 내에 안전하게 도착해요.")}</AccordionContent>
          </AccordionItem>
          <AccordionItem value="1">
            <AccordionTrigger title="반품/교환은 어떻게 하나요?" description="구매 후 7일 이내 신청" prefix={<IconDeliveryRegular style={{ width: 20, height: 20 }} />} />
            <AccordionContent>{renderContent("상품 상세페이지의 [반품/교환 신청] 버튼을 눌러 접수해주세요.")}</AccordionContent>
          </AccordionItem>
          <AccordionItem value="2" disabled>
            <AccordionTrigger title="고객센터 문의하기" prefix={<IconDeliveryRegular style={{ width: 20, height: 20 }} />} />
            <AccordionContent>{renderContent("운영시간은 평일 09:00 ~ 18:00 입니다.")}</AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  );
}

function ActionButtonDemo() {
  const stateVariants = [
    { key: 'neutralSolid', label: 'Neutral Solid' },
    { key: 'brandSolid', label: 'Brand Solid' },
    { key: 'criticalSolid', label: 'Critical Solid' },
    { key: 'neutralWeak', label: 'Neutral Weak' },
    { key: 'brandOutline', label: 'Brand Outline' },
    { key: 'neutralOutline', label: 'Neutral Outline' },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x7)', width: '100%', maxWidth: 480, margin: '0 auto' }}>
      {/* 1. Hierarchy & State Matrix */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x3)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', textAlign: 'center' }}>
          Hierarchy & States (Enabled / Loading / Disabled)
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 'var(--seed-dimension-x2_5)', width: '100%', textAlign: 'center', fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-subtle)' }}>
          <span>Enabled</span>
          <span>Loading</span>
          <span>Disabled</span>
        </div>

        {stateVariants.map(({ key }) => (
          <div key={key} style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 'var(--seed-dimension-x2_5)', width: '100%', alignItems: 'center' }}>
            <ActionButton variant={key} size="medium" style={{ width: '100%' }}>
              Enabled
            </ActionButton>

            <ActionButton variant={key} size="medium" loading style={{ width: '100%' }}>
              Loading
            </ActionButton>

            <ActionButton variant={key} size="medium" disabled style={{ width: '100%' }}>
              Disabled
            </ActionButton>
          </div>
        ))}
      </div>

      {/* 2. Sizes & Layouts */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x3)', width: '100%', alignItems: 'center' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Sizes & Layouts
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--seed-dimension-x2)', justifyContent: 'center', alignItems: 'center' }}>
          <ActionButton variant="brandSolid" size="medium">
            <PrefixIcon svg={<IconAddRegular />} />
            글쓰기
          </ActionButton>
          <ActionButton variant="neutralWeak" size="medium">
            더보기
            <SuffixIcon svg={<IconChevronRightRegular />} />
          </ActionButton>
          <ActionButton variant="neutralOutline" size="medium" layout="iconOnly" aria-label="관심">
            <Icon svg={<IconHeartRegular />} />
          </ActionButton>
          <ActionButton variant="neutralWeak" size="xsmall">
            필터 (XSmall)
          </ActionButton>
          <ActionButton variant="brandSolid" size="large">
            구매하기 (Large)
          </ActionButton>
        </div>
      </div>
    </div>
  );
}

function AttachmentFieldDemo() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x7)', width: '100%', maxWidth: 420, margin: '0 auto' }}>
      {/* 1. Standard Input */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Standard Input (CLI Component)
        </div>
        <AttachmentField label="증빙 파일 업로드" description="최대 5개까지 업로드할 수 있습니다." maxFiles={5}>
          <AttachmentInput />
        </AttachmentField>
      </div>

      {/* 2. Dropzone Variant */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Dropzone (CLI Component)
        </div>
        <AttachmentField label="드래그 앤 드롭 업로드" maxFiles={5}>
          <AttachmentDropzone />
        </AttachmentField>
      </div>
    </div>
  );
}

const COMPONENTS = [
  {
    name: 'Accordion',
    slug: 'ui:accordion',
    demo: <AccordionDemo />,
  },

  {
    name: 'Action Button',
    slug: 'ui:action-button',
    demo: <ActionButtonDemo />,
  },

  {
    name: 'Alert Dialog',
    slug: 'ui:alert-dialog',
    demo: <AlertDialogDemo />,
  },

  {
    name: 'Attachment Field',
    slug: 'ui:attachment-field',
    demo: <AttachmentFieldDemo />,
  },

  {
    name: 'Avatar',
    slug: 'ui:avatar',
    demo: <AvatarDemo />,
  },
];

export function ComponentGallery() {
  const [cur, setCur] = useState(0);
  const wrapRef = useRef(null);
  const navRef = useRef(null);
  const total = COMPONENTS.length;

  const go = (idx) => {
    if (idx < 0) idx = 0;
    if (idx >= total) idx = total - 1;
    setCur(idx);
  };

  useEffect(() => {
    if (wrapRef.current) {
      wrapRef.current.scrollTo({
        left: cur * wrapRef.current.clientWidth,
        behavior: 'smooth',
      });
    }
    if (navRef.current) {
      const activeBtn = navRef.current.children[cur];
      if (activeBtn) {
        activeBtn.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'center' });
      }
    }
  }, [cur]);

  return (
    <section className="comp-gallery-container" id="showcase">
      {/* 토글 네비 */}
      <div className="comp-nav" ref={navRef}>
        {COMPONENTS.map((c, i) => (
          <button
            key={c.name}
            className={`comp-nav-btn${i === cur ? ' active' : ''}`}
            onClick={() => go(i)}
          >
            {c.name}
          </button>
        ))}
      </div>

      {/* 상단 정보 바 (컴포넌트 이름/슬러그, dot 인디케이터, 이전/다음 화살표) */}
      <div className="comp-info-bar" style={{ marginBlock: 'var(--seed-dimension-x3_5)' }}>
        <div>
          <div className="comp-name">{COMPONENTS[cur].name}</div>
          <div className="comp-slug">{COMPONENTS[cur].slug}</div>
        </div>
        <div className="comp-dots" style={{ marginTop: 0 }}>
          {COMPONENTS.map((_, i) => (
            <button
              key={i}
              className={`comp-dot${i === cur ? ' active' : ''}`}
              onClick={() => go(i)}
              aria-label={COMPONENTS[i].name}
            />
          ))}
        </div>
        <div className="comp-arrows">
          <button className="comp-arrow-btn" onClick={() => go(cur - 1)} disabled={cur === 0}>‹</button>
          <button className="comp-arrow-btn" onClick={() => go(cur + 1)} disabled={cur === total - 1}>›</button>
        </div>
      </div>

      {/* 캐러셀 */}
      <div className="comp-carousel-wrap">
        <div className="comp-carousel-track" style={{ transform: `translateX(-${cur * 100}%)` }}>
          {COMPONENTS.map((c, i) => (
            <div key={c.name} className={`comp-carousel-slide${i === cur ? ' active' : ''}`}>
              {c.demo}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
