/**
 * [컴포넌트 갤러리 쇼케이스]
 * - 100% SEED CLI 컴포넌트 (`npx @seed-design/cli add ui:*`) 기반
 * - 100% SEED Design System 시맨틱 CSS 토큰 (`var(--seed-*)`) 적용
 */

import React, { useState, useRef, useEffect } from 'react';
import {
  IconDeliveryRegular,
  IconAddRegular,
  IconChevronRightRegular,
  IconHeartRegular,
} from "@seed-design/icon";
import {
  IconCheckmarkCircleFill,
  IconCheckmarkFlowerFill,
  IconCheckmarkShieldFill,
  IconPersonFill,
  IconStoreFill,
  IconHouseFill,
  IconBuilding2Fill,
  IconLocationpinFill,
  IconDot3HorizontalChatbubbleLeftFill,
  IconBellFill,
  IconPlusLine,
} from "@karrotmarket/react-monochrome-icon";

// Import CLI React UI components generated by npx @seed-design/cli add ui:*
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '../components/ui/accordion';
import { ActionButton, PrefixIcon, SuffixIcon, Icon } from '../components/ui/action-button';
import { Avatar, AvatarBadge, AvatarStack } from '../components/ui/avatar';
import { AttachmentField, AttachmentInput, AttachmentDropzone } from '../components/ui/attachment-field';
import { AttachmentDisplayField, AttachmentDisplay } from '../components/ui/attachment-display-field';
import { Callout, ActionableCallout, DismissibleCallout } from '../components/ui/callout';
import { Checkbox, CheckboxGroup } from '../components/ui/checkbox';
import { Chip } from '../components/ui/chip';
import { ChipTabsRoot, ChipTabsList, ChipTabsTrigger } from '../components/ui/chip-tabs';
import { ContentPlaceholder } from '../components/ui/content-placeholder';
import { ContextualFloatingButton } from '../components/ui/contextual-floating-button';
import { DatePicker, TwoMonthDatePicker, WeekDatePicker, ContinuousDatePicker } from '../components/ui/date-picker';
import { Float } from '../components/ui/layout';
import {
  BottomSheetRoot,
  BottomSheetTrigger,
  BottomSheetContent,
  BottomSheetBody,
  BottomSheetFooter,
} from '../components/ui/bottom-sheet';
import {
  AlertDialogRoot,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogAction,
} from '../components/ui/alert-dialog';
import { Badge } from '../components/ui/badge';

// Alert Dialog Layout Variants
const ALERT_DIALOG_LAYOUTS = [
  {
    key: 'single', label: 'Single',
    title: 'Title은 작성을 권장해요', desc: '본문 내용을 입력해주세요.',
    kind: 'pair', buttons: [{ variant: 'neutralSolid', label: '라벨' }],
  },
  {
    key: 'neutral', label: 'Neutral',
    title: 'Title은 작성을 권장해요', desc: '본문 내용을 입력해주세요.',
    kind: 'pair', buttons: [{ variant: 'neutralWeak', label: '라벨' }, { variant: 'neutralSolid', label: '라벨' }],
  },
  {
    key: 'neutralOverflow', label: 'Neutral (Overflow)',
    title: 'Title은 작성을 권장해요', desc: '본문 내용을 입력해주세요.',
    kind: 'pair', buttons: [{ variant: 'neutralWeak', label: '취소할래요' }, { variant: 'neutralSolid', label: '네 확인했어요 진행할게요' }],
  },
  {
    key: 'critical', label: 'Critical',
    title: '삭제하시겠어요?', desc: '삭제한 게시글은 복구할 수 없어요.',
    kind: 'pair', buttons: [{ variant: 'neutralWeak', label: '취소' }, { variant: 'criticalSolid', label: '삭제' }],
  },
  {
    key: 'criticalOverflow', label: 'Critical (Overflow)',
    title: '삭제하시겠어요?', desc: '삭제한 게시글은 복구할 수 없어요.',
    kind: 'pair', buttons: [{ variant: 'neutralWeak', label: '취소할래요' }, { variant: 'criticalSolid', label: '네 삭제할게요 진행할게요' }],
  },
  {
    key: 'nonePreferred', label: 'NonePreferred',
    title: 'Title은 작성을 권장해요', desc: '본문 내용을 입력해주세요.',
    kind: 'stack', buttons: [{ variant: 'neutralSolid', label: '라벨' }, { variant: 'ghost', label: '라벨', muted: true }],
  },
];

function AlertDialogDemo() {
  const [selectedLayoutKey, setSelectedLayoutKey] = useState('single');
  const layout = ALERT_DIALOG_LAYOUTS.find((l) => l.key === selectedLayoutKey) || ALERT_DIALOG_LAYOUTS[0];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x4)', width: '100%', maxWidth: 360, margin: '0 auto' }}>
      {/* Layout Variant Selector Tabs */}
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--seed-dimension-x1_5)', justifyContent: 'center' }}>
        {ALERT_DIALOG_LAYOUTS.map((l) => (
          <button
            key={l.key}
            type="button"
            className={`comp-nav-btn${l.key === selectedLayoutKey ? ' active' : ''}`}
            onClick={() => setSelectedLayoutKey(l.key)}
            style={{ fontSize: 'var(--seed-font-size-t2)', paddingInline: 'var(--seed-dimension-x2)', paddingBlock: 'var(--seed-dimension-x1)' }}
          >
            {l.label}
          </button>
        ))}
      </div>

      {/* Selected Layout Dialog Card */}
      <div style={{ position: 'relative', width: '100%' }}>
        <AlertDialogRoot open={true}>
          <AlertDialogContent style={{ width: '100%', position: 'relative', transform: 'none' }}>
            <AlertDialogHeader>
              <AlertDialogTitle>{layout.title}</AlertDialogTitle>
              {layout.desc && <AlertDialogDescription>{layout.desc}</AlertDialogDescription>}
            </AlertDialogHeader>
            <AlertDialogFooter>
              {layout.kind === 'stack' ? (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2)', alignItems: 'stretch', width: '100%' }}>
                  {layout.buttons.map((b, i) => (
                    <AlertDialogAction
                      key={i}
                      variant={b.variant}
                      size="medium"
                      style={b.muted ? { color: 'var(--seed-color-fg-neutral-muted)', fontWeight: 'var(--seed-font-weight-bold)' } : undefined}
                    >
                      {b.label}
                    </AlertDialogAction>
                  ))}
                </div>
              ) : (
                <div style={{ display: 'flex', flexWrap: 'wrap-reverse', gap: 'var(--seed-dimension-x2)', width: '100%' }}>
                  {layout.buttons.map((b, i) => (
                    <AlertDialogAction
                      key={i}
                      variant={b.variant}
                      size="medium"
                      style={{
                        flexGrow: 1,
                        minWidth: `calc(${100 / layout.buttons.length}% - var(--seed-dimension-x2) / ${layout.buttons.length})`,
                      }}
                    >
                      {b.label}
                    </AlertDialogAction>
                  ))}
                </div>
              )}
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialogRoot>
      </div>
    </div>
  );
}

function AvatarDemo() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x7)', width: '100%', alignItems: 'center' }}>
      {/* 1. Sizes */}
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Sizes (24px ~ 96px)
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--seed-dimension-x3)', alignItems: 'center', justifyContent: 'center' }}>
          {['24', '36', '48', '64', '80', '96'].map((sz) => (
            <div key={sz} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x1)' }}>
              <Avatar size={sz} fallback={<IconPersonFill style={{ width: '60%', height: '60%', color: 'var(--seed-color-fg-neutral-subtle)' }} />} alt={`Avatar ${sz}`} />
              <span style={{ fontSize: 'var(--seed-font-size-t2)', color: 'var(--seed-color-fg-neutral-muted)' }}>{sz}px</span>
            </div>
          ))}
        </div>
      </div>

      {/* 2. Badge & Mask */}
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Badge & Mask (Circle, Flower, Shield)
        </div>
        <div style={{ display: 'flex', gap: 'var(--seed-dimension-x5)', alignItems: 'center', justifyContent: 'center' }}>
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x1_5)' }}>
            <Avatar size="64" badgeMask="circle" fallback={<IconPersonFill style={{ width: '60%', height: '60%', color: 'var(--seed-color-fg-neutral-subtle)' }} />} alt="Avatar">
              <AvatarBadge>
                <IconCheckmarkCircleFill style={{ width: '100%', height: '100%', color: 'var(--seed-color-palette-green-600)' }} />
              </AvatarBadge>
            </Avatar>
            <span style={{ fontSize: 'var(--seed-font-size-t3)', color: 'var(--seed-color-fg-neutral-subtle)' }}>Circle Badge</span>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x1_5)' }}>
            <Avatar size="64" badgeMask="flower" fallback={<IconPersonFill style={{ width: '60%', height: '60%', color: 'var(--seed-color-fg-neutral-subtle)' }} />} alt="Avatar">
              <AvatarBadge>
                <IconCheckmarkFlowerFill style={{ width: '100%', height: '100%', color: 'var(--seed-color-palette-green-600)' }} />
              </AvatarBadge>
            </Avatar>
            <span style={{ fontSize: 'var(--seed-font-size-t3)', color: 'var(--seed-color-fg-neutral-subtle)' }}>Flower Badge</span>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x1_5)' }}>
            <Avatar size="64" badgeMask="shield" fallback={<IconPersonFill style={{ width: '60%', height: '60%', color: 'var(--seed-color-fg-neutral-subtle)' }} />} alt="Avatar">
              <AvatarBadge>
                <IconCheckmarkShieldFill style={{ width: '100%', height: '100%', color: 'var(--seed-color-palette-blue-600)' }} />
              </AvatarBadge>
            </Avatar>
            <span style={{ fontSize: 'var(--seed-font-size-t3)', color: 'var(--seed-color-fg-neutral-subtle)' }}>Shield Badge</span>
          </div>
        </div>
      </div>

      {/* 3. Avatar Stack */}
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Avatar Stack
        </div>
        <AvatarStack size="48">
          {[0, 1, 2, 3].map((idx) => (
            <Avatar key={idx} size="48" fallback={<IconPersonFill style={{ width: '60%', height: '60%', color: 'var(--seed-color-fg-neutral-subtle)' }} />} alt={`User ${idx}`} />
          ))}
        </AvatarStack>
      </div>

      {/* 4. Fallback */}
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Fallback Placeholders
        </div>
        <div style={{ display: 'flex', gap: 'var(--seed-dimension-x5)', alignItems: 'center', justifyContent: 'center' }}>
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x1_5)' }}>
            <Avatar size="64" fallback={<IconPersonFill style={{ width: '60%', height: '60%', color: 'var(--seed-color-fg-neutral-subtle)' }} />} />
            <span style={{ fontSize: 'var(--seed-font-size-t3)', color: 'var(--seed-color-fg-neutral-subtle)' }}>Person</span>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x1_5)' }}>
            <Avatar size="64" fallback={<IconStoreFill style={{ width: '55%', height: '55%', color: 'var(--seed-color-fg-neutral-subtle)' }} />} />
            <span style={{ fontSize: 'var(--seed-font-size-t3)', color: 'var(--seed-color-fg-neutral-subtle)' }}>Business</span>
          </div>
        </div>
      </div>
    </div>
  );
}

function AccordionDemo() {
  const renderContent = (text) => (
    <div
      style={{
        paddingInline: 'var(--seed-dimension-spacing-x-global-gutter)',
        paddingTop: 'var(--seed-dimension-x2)',
        paddingBottom: 'var(--seed-dimension-x3)',
        fontSize: 'var(--seed-font-size-t4)',
        lineHeight: 'var(--seed-line-height-t4)',
        color: 'var(--seed-color-fg-neutral-subtle)',
      }}
    >
      {text}
    </div>
  );

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x6)', width: '100%', maxWidth: 360, margin: '0 auto' }}>
      {/* 1. Inline Variant */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2)' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Variant: Inline
        </div>
        <Accordion defaultValue={["1"]} variant="inline" style={{ width: '100%' }}>
          <AccordionItem value="0">
            <AccordionTrigger title="배송 방법 안내" prefix={<IconDeliveryRegular style={{ width: 20, height: 20 }} />} />
            <AccordionContent>{renderContent("기본 배송은 당일 발송되며 1~2일 내에 안전하게 도착해요.")}</AccordionContent>
          </AccordionItem>
          <AccordionItem value="1">
            <AccordionTrigger title="반품/교환은 어떻게 하나요?" description="구매 후 7일 이내 신청" prefix={<IconDeliveryRegular style={{ width: 20, height: 20 }} />} />
            <AccordionContent>{renderContent("상품 상세페이지의 [반품/교환 신청] 버튼을 눌러 접수해주세요.")}</AccordionContent>
          </AccordionItem>
          <AccordionItem value="2" disabled>
            <AccordionTrigger title="고객센터 문의하기" prefix={<IconDeliveryRegular style={{ width: 20, height: 20 }} />} />
            <AccordionContent>{renderContent("운영시간은 평일 09:00 ~ 18:00 입니다.")}</AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>

      {/* 2. Separated Variant */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2)' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Variant: Separated
        </div>
        <Accordion defaultValue={["1"]} variant="separated" style={{ width: '100%' }}>
          <AccordionItem value="0">
            <AccordionTrigger title="배송 방법 안내" prefix={<IconDeliveryRegular style={{ width: 20, height: 20 }} />} />
            <AccordionContent>{renderContent("기본 배송은 당일 발송되며 1~2일 내에 안전하게 도착해요.")}</AccordionContent>
          </AccordionItem>
          <AccordionItem value="1">
            <AccordionTrigger title="반품/교환은 어떻게 하나요?" description="구매 후 7일 이내 신청" prefix={<IconDeliveryRegular style={{ width: 20, height: 20 }} />} />
            <AccordionContent>{renderContent("상품 상세페이지의 [반품/교환 신청] 버튼을 눌러 접수해주세요.")}</AccordionContent>
          </AccordionItem>
          <AccordionItem value="2" disabled>
            <AccordionTrigger title="고객센터 문의하기" prefix={<IconDeliveryRegular style={{ width: 20, height: 20 }} />} />
            <AccordionContent>{renderContent("운영시간은 평일 09:00 ~ 18:00 입니다.")}</AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  );
}

function ActionButtonDemo() {
  const stateVariants = [
    { key: 'neutralSolid', label: 'Neutral Solid' },
    { key: 'brandSolid', label: 'Brand Solid' },
    { key: 'criticalSolid', label: 'Critical Solid' },
    { key: 'neutralWeak', label: 'Neutral Weak' },
    { key: 'brandOutline', label: 'Brand Outline' },
    { key: 'neutralOutline', label: 'Neutral Outline' },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x7)', width: '100%', maxWidth: 480, margin: '0 auto' }}>
      {/* 1. Hierarchy & State Matrix */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x3)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', textAlign: 'center' }}>
          Hierarchy & States (Enabled / Loading / Disabled)
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 'var(--seed-dimension-x2_5)', width: '100%', textAlign: 'center', fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-subtle)' }}>
          <span>Enabled</span>
          <span>Loading</span>
          <span>Disabled</span>
        </div>

        {stateVariants.map(({ key }) => (
          <div key={key} style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 'var(--seed-dimension-x2_5)', width: '100%', alignItems: 'center' }}>
            <ActionButton variant={key} size="medium" style={{ width: '100%' }}>
              Enabled
            </ActionButton>

            <ActionButton variant={key} size="medium" loading style={{ width: '100%' }}>
              Loading
            </ActionButton>

            <ActionButton variant={key} size="medium" disabled style={{ width: '100%' }}>
              Disabled
            </ActionButton>
          </div>
        ))}
      </div>

      {/* 2. Sizes & Layouts */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x3)', width: '100%', alignItems: 'center' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Sizes & Layouts
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--seed-dimension-x2)', justifyContent: 'center', alignItems: 'center' }}>
          <ActionButton variant="brandSolid" size="medium">
            <PrefixIcon svg={<IconAddRegular />} />
            글쓰기
          </ActionButton>
          <ActionButton variant="neutralWeak" size="medium">
            더보기
            <SuffixIcon svg={<IconChevronRightRegular />} />
          </ActionButton>
          <ActionButton variant="neutralOutline" size="medium" layout="iconOnly" aria-label="관심">
            <Icon svg={<IconHeartRegular />} />
          </ActionButton>
          <ActionButton variant="neutralWeak" size="xsmall">
            필터 (XSmall)
          </ActionButton>
          <ActionButton variant="brandSolid" size="large">
            구매하기 (Large)
          </ActionButton>
        </div>
      </div>
    </div>
  );
}

function AttachmentDemo() {
  const sampleEntries = [
    {
      id: "1",
      thumbnailUrl: "https://picsum.photos/seed/attachment1/200/200",
      status: "success",
    },
    {
      id: "2",
      thumbnailUrl: "https://picsum.photos/seed/attachment2/200/200",
      status: "success",
    },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x7)', width: '100%', maxWidth: 460, margin: '0 auto' }}>
      {/* 1. Attachment Field (Standard File Upload) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          1. Attachment Field (Local File Upload)
        </div>
        <AttachmentField label="증빙 파일 업로드" description="최대 5개까지 업로드할 수 있습니다." maxFiles={5}>
          <AttachmentInput />
        </AttachmentField>
      </div>

      {/* 2. Dropzone Variant */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          2. Dropzone Variant
        </div>
        <AttachmentField label="드래그 앤 드롭 업로드" maxFiles={5}>
          <AttachmentDropzone />
        </AttachmentField>
      </div>

      {/* 3. Attachment Display Field (URL Thumbnail Display) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          3. Attachment Display Field (URL Thumbnail Preview)
        </div>
        <AttachmentDisplayField label="첨부 미디어 썸네일 (URL)" description="서버에 업로드된 미디어 리소스 썸네일 미리보기" defaultEntries={sampleEntries} maxEntries={5}>
          <AttachmentDisplay
            onTriggerClick={({ addEntries }) => {
              const newId = Math.random().toString(36).substring(7);
              addEntries([
                {
                  id: newId,
                  thumbnailUrl: `https://picsum.photos/seed/${newId}/200/200`,
                  status: "success",
                },
              ]);
            }}
          />
        </AttachmentDisplayField>
      </div>
    </div>
  );
}

function BadgeDemo() {
  const tones = [
    { key: 'neutral', label: 'Neutral' },
    { key: 'brand', label: 'Brand' },
    { key: 'informative', label: 'Informative' },
    { key: 'positive', label: 'Positive' },
    { key: 'warning', label: 'Warning' },
    { key: 'critical', label: 'Critical' },
  ];
  const variants = ['solid', 'weak', 'outline'];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x6)', width: '100%', maxWidth: 420, margin: '0 auto' }}>
      {/* Tone & Variant Matrix */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x3)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', textAlign: 'center' }}>
          Badge Tones & Variants (Medium Size)
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '80px repeat(3, 1fr)', gap: 'var(--seed-dimension-x2)', alignItems: 'center', textAlign: 'center' }}>
          <span style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-subtle)', textAlign: 'left' }}>Tone</span>
          <span style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-subtle)' }}>Solid</span>
          <span style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-subtle)' }}>Weak</span>
          <span style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-subtle)' }}>Outline</span>

          {tones.map(({ key, label }) => (
            <React.Fragment key={key}>
              <span style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textAlign: 'left' }}>{label}</span>
              {variants.map((v) => (
                <div key={v} style={{ display: 'flex', justifyContent: 'center' }}>
                  <Badge tone={key} variant={v} size="medium">
                    라벨
                  </Badge>
                </div>
              ))}
            </React.Fragment>
          ))}
        </div>
      </div>

      {/* Sizes Comparison */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2_5)', width: '100%', alignItems: 'center' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Sizes (Medium / Large)
        </div>
        <div style={{ display: 'flex', gap: 'var(--seed-dimension-x4)', alignItems: 'center' }}>
          <Badge tone="brand" variant="solid" size="medium">
            Medium
          </Badge>
          <Badge tone="brand" variant="solid" size="large">
            Large
          </Badge>
        </div>
      </div>
    </div>
  );
}

function BottomNavigationDemo() {
  const [activeTab, setActiveTab] = useState(0);

  const tabs = [
    { label: '홈', icon: <IconHouseFill style={{ width: 22, height: 22 }} />, badge: null },
    { label: '내회사', icon: <IconBuilding2Fill style={{ width: 22, height: 22 }} />, badge: null },
    { label: '내 근처', icon: <IconLocationpinFill style={{ width: 22, height: 22 }} />, badge: null },
    { label: '채팅', icon: <IconDot3HorizontalChatbubbleLeftFill style={{ width: 22, height: 22 }} />, badge: '3' },
    { label: '프로필', icon: <IconPersonFill style={{ width: 22, height: 22 }} />, badge: null },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x6)', width: '100%', maxWidth: 480, margin: '0 auto' }}>
      <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', textAlign: 'center' }}>
        5 Tabs Max · Fill Icons · Max Width 480px · Notification Badge
      </div>

      {/* Bottom Navigation Mock Phone Container */}
      <div
        style={{
          width: '100%',
          background: 'var(--seed-color-bg-layer-default)',
          border: '1px solid var(--seed-color-stroke-neutral-weak)',
          borderRadius: 'var(--seed-dimension-x4)',
          boxShadow: 'var(--seed-elevation-s2, 0 4px 20px rgba(0,0,0,0.06))',
          overflow: 'hidden',
        }}
      >
        {/* Screen Mock Area */}
        <div style={{ height: 120, background: 'var(--seed-color-bg-neutral-weak)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 'var(--seed-font-size-t3)', color: 'var(--seed-color-fg-neutral-subtle)' }}>
          선택된 탭: <strong style={{ color: 'var(--seed-color-fg-brand)', marginLeft: 'var(--seed-dimension-x1_5)' }}>{tabs[activeTab].label}</strong>
        </div>

        {/* Bottom Navigation Bar */}
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(5, 1fr)',
            height: 56,
            background: 'var(--seed-color-bg-layer-default)',
            borderTop: '1px solid var(--seed-color-stroke-neutral-weak)',
            position: 'relative',
          }}
        >
          {tabs.map((t, idx) => {
            const isActive = idx === activeTab;
            return (
              <button
                key={t.label}
                onClick={() => setActiveTab(idx)}
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: 'var(--seed-dimension-x0_5)',
                  border: 'none',
                  background: 'transparent',
                  cursor: 'pointer',
                  padding: 0,
                  position: 'relative',
                  color: isActive ? 'var(--seed-color-fg-neutral)' : 'var(--seed-color-fg-neutral-subtle)',
                  transition: 'color 0.15s ease',
                }}
              >
                <div style={{ position: 'relative', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  {t.icon}
                  {t.badge && (
                    <span
                      style={{
                        position: 'absolute',
                        top: -3,
                        right: -8,
                        background: 'var(--seed-color-bg-critical-solid)',
                        color: 'var(--seed-color-palette-static-white)',
                        fontSize: 'var(--seed-font-size-t1)',
                        fontWeight: 'var(--seed-font-weight-bold)',
                        height: 15,
                        minWidth: 15,
                        padding: '0 var(--seed-dimension-x1)',
                        borderRadius: 999,
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        lineHeight: 1,
                      }}
                    >
                      {t.badge}
                    </span>
                  )}
                </div>
                <span style={{ fontSize: 'var(--seed-font-size-t1)', fontWeight: isActive ? 'var(--seed-font-weight-bold)' : 'var(--seed-font-weight-regular)' }}>
                  {t.label}
                </span>
              </button>
            );
          })}
        </div>
      </div>
    </div>
  );
}

function BottomSheetDemo() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x6)', width: '100%', maxWidth: 460, margin: '0 auto' }}>
      <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', textAlign: 'center' }}>
        Inline Preview & Interactive Modal · Max Width 480px
      </div>

      {/* Inline Permanent Sheet Preview */}
      <div
        style={{
          width: '100%',
          height: 280,
          background: 'var(--seed-color-bg-neutral-weak)',
          borderRadius: 'var(--seed-dimension-x4)',
          border: '1px solid var(--seed-color-stroke-neutral-weak)',
          boxShadow: 'var(--seed-elevation-s2, 0 4px 20px rgba(0,0,0,0.06))',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'flex-end',
          position: 'relative',
          overflow: 'hidden',
        }}
      >
        {/* Backdrop overlay */}
        <div style={{ position: 'absolute', inset: 0, background: 'rgba(0,0,0,0.25)' }} />

        {/* Bottom Sheet Modal Frame */}
        <div
          style={{
            position: 'relative',
            zIndex: 1,
            background: 'var(--seed-color-bg-layer-default)',
            borderTopLeftRadius: 'var(--seed-dimension-x4)',
            borderTopRightRadius: 'var(--seed-dimension-x4)',
            padding: 'var(--seed-dimension-x4)',
            display: 'flex',
            flexDirection: 'column',
            gap: 'var(--seed-dimension-x3)',
            boxShadow: '0 -4px 16px rgba(0,0,0,0.08)',
          }}
        >
          {/* Drag Handle */}
          <div style={{ width: 36, height: 4, background: 'var(--seed-color-stroke-neutral-muted, #CBD5E1)', borderRadius: 999, margin: '0 auto var(--seed-dimension-x1)' }} />

          {/* Header */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x1)' }}>
            <div style={{ fontSize: 'var(--seed-font-size-t5)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral)' }}>
              하단 모달 바텀시트
            </div>
            <div style={{ fontSize: 'var(--seed-font-size-t2)', color: 'var(--seed-color-fg-neutral-subtle)' }}>
              SEED 2.0 하단 슬라이드 모달 컴포넌트입니다.
            </div>
          </div>

          {/* Body */}
          <div style={{ fontSize: 'var(--seed-font-size-t3)', color: 'var(--seed-color-fg-neutral)', lineHeight: 1.5 }}>
            하단 모달 바텀시트는 화면 하단에서 올라오며 최대 480px 너비를 지원합니다.
          </div>

          {/* Footer */}
          <ActionButton variant="brandSolid" size="medium" style={{ width: '100%' }}>
            확인 및 닫기
          </ActionButton>
        </div>
      </div>

      {/* Trigger Modal Button */}
      <div style={{ display: 'flex', justifyContent: 'center' }}>
        <BottomSheetRoot>
          <BottomSheetTrigger asChild>
            <ActionButton variant="neutralOutline" size="medium">
              실제 팝업 모달 테스트
            </ActionButton>
          </BottomSheetTrigger>
          <BottomSheetContent title="하단 모달 바텀시트" description="SEED 2.0 하단 슬라이드 모달 컴포넌트입니다.">
            <BottomSheetBody>
              <div style={{ padding: 'var(--seed-dimension-x3) 0', fontSize: 'var(--seed-font-size-t4)', color: 'var(--seed-color-fg-neutral)', lineHeight: 1.6 }}>
                하단 모달 바텀시트는 최대 480px 너비를 유지하며, 드래그/배경 터치 닫기 동작 및 접근성(a11y) 속성을 자동 관리합니다.
              </div>
            </BottomSheetBody>
            <BottomSheetFooter>
              <ActionButton variant="brandSolid" size="large" style={{ width: '100%' }}>
                확인 및 닫기
              </ActionButton>
            </BottomSheetFooter>
          </BottomSheetContent>
        </BottomSheetRoot>
      </div>
    </div>
  );
}

function CalloutDemo() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x6)', width: '100%', maxWidth: 460, margin: '0 auto' }}>
      <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', textAlign: 'center' }}>
        Display · Actionable · Dismissible (6 Tones)
      </div>

      {/* 1. Static Display Callouts */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x3)', width: '100%' }}>
        <Callout
          tone="informative"
          title="안내"
          description="기능에 대한 주요 정보 및 팁을 시각적으로 강조하여 전달합니다."
          prefixIcon={<IconCheckmarkCircleFill />}
        />
        <Callout
          tone="warning"
          title="주의"
          description="중요한 설정 변경 전 주의가 필요합니다."
        />
        <Callout
          tone="magic"
          title="새 기능"
          description="프리미엄 AI 유틸리티 기능이 새로 추가되었습니다!"
        />
      </div>

      {/* 2. Actionable & Dismissible */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x3)', width: '100%' }}>
        <ActionableCallout
          tone="neutral"
          title="이동"
          description="선택하여 하위 메뉴나 상세 페이지로 바로 이동합니다."
        />
        <DismissibleCallout
          tone="positive"
          title="성공"
          description="새로운 프로필 정보 저장이 완료되었습니다."
        />
      </div>
    </div>
  );
}

function CheckboxDemo() {
  const [checkedItems, setCheckedItems] = useState([true, false, true]);

  const allChecked = checkedItems.every(Boolean);
  const isIndeterminate = checkedItems.some(Boolean) && !allChecked;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x6)', width: '100%', maxWidth: 420, margin: '0 auto' }}>
      <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', textAlign: 'center' }}>
        Square & Ghost · Sizes (Medium/Large) · Indeterminate Parent Group
      </div>

      {/* 1. Shapes & Sizes */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x3)', width: '100%' }}>
        <CheckboxGroup label="알림 동의 항목 (Square)" indicator="필수">
          <Checkbox label="서비스 이용약관 동의 (Large, Bold)" size="large" weight="bold" defaultChecked tone="neutral" />
          <Checkbox label="개인정보 처리방침 동의 (Medium)" size="medium" defaultChecked tone="neutral" />
        </CheckboxGroup>

        <CheckboxGroup label="마케팅 수신 항목 (Ghost)" indicator="선택">
          <Checkbox label="이메일 마케팅 알림" variant="ghost" size="medium" defaultChecked tone="neutral" />
          <Checkbox label="SMS 마케팅 알림" variant="ghost" size="medium" tone="neutral" />
        </CheckboxGroup>
      </div>

      {/* 2. Parent-Child Indeterminate Group */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x3)', width: '100%' }}>
        <CheckboxGroup label="약관 전체 동의 그룹 (Parent/Child)">
          <Checkbox
            label="전체 동의하기"
            size="large"
            weight="bold"
            checked={allChecked}
            indeterminate={isIndeterminate}
            onCheckedChange={(checked) => setCheckedItems([Boolean(checked), Boolean(checked), Boolean(checked)])}
          />
          <div style={{ paddingLeft: 'var(--seed-dimension-x5)', display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2)' }}>
            <Checkbox
              label="[필수] 서비스 약관 동의"
              size="medium"
              checked={checkedItems[0]}
              onCheckedChange={(checked) => setCheckedItems([Boolean(checked), checkedItems[1], checkedItems[2]])}
            />
            <Checkbox
              label="[필수] 개인정보 제공 동의"
              size="medium"
              checked={checkedItems[1]}
              onCheckedChange={(checked) => setCheckedItems([checkedItems[0], Boolean(checked), checkedItems[2]])}
            />
            <Checkbox
              label="[선택] 혜택 알림 수신 동의"
              size="medium"
              checked={checkedItems[2]}
              onCheckedChange={(checked) => setCheckedItems([checkedItems[0], checkedItems[1], Boolean(checked)])}
            />
          </div>
        </CheckboxGroup>
      </div>
    </div>
  );
}

function ChipDemo() {
  const [radioVal, setRadioVal] = useState("all");
  const [tabVal, setTabVal] = useState("1");

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x7)', width: '100%', maxWidth: 460, margin: '0 auto' }}>
      <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', textAlign: 'center' }}>
        Button & Toggle · Radio Selection · Chip Tabs
      </div>

      {/* 1. Chip Button & Toggle */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          1. Button & Toggle Chips
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--seed-dimension-x2)', alignItems: 'center' }}>
          <Chip.Button size="medium" variant="solid">
            <Chip.Label>Solid Button</Chip.Label>
          </Chip.Button>
          <Chip.Button size="medium" variant="outlineStrong">
            <Chip.Label>Outline Strong</Chip.Label>
          </Chip.Button>
          <Chip.Toggle size="medium" defaultChecked>
            <Chip.Label>Toggle (Checked)</Chip.Label>
          </Chip.Toggle>
          <Chip.Toggle size="medium" variant="ghost">
            <Chip.Label>Ghost Toggle</Chip.Label>
          </Chip.Toggle>
        </div>
      </div>

      {/* 2. Chip Radio Selection */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          2. Radio Single Selection (Chip.RadioGroup)
        </div>
        <Chip.RadioRoot value={radioVal} onValueChange={setRadioVal} aria-label="필터 선택">
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--seed-dimension-x2)' }}>
            <Chip.RadioItem value="all" size="medium">
              <Chip.Label>전체</Chip.Label>
            </Chip.RadioItem>
            <Chip.RadioItem value="tech" size="medium">
              <Chip.Label>개발/기술</Chip.Label>
            </Chip.RadioItem>
            <Chip.RadioItem value="design" size="medium">
              <Chip.Label>디자인</Chip.Label>
            </Chip.RadioItem>
            <Chip.RadioItem value="career" size="medium">
              <Chip.Label>커리어</Chip.Label>
            </Chip.RadioItem>
          </div>
        </Chip.RadioRoot>
      </div>

      {/* 3. Chip Tabs Navigation */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x2_5)', width: '100%' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          3. Chip Tabs (Category Navigation)
        </div>
        <ChipTabsRoot variant="neutralSolid" size="medium" value={tabVal} onValueChange={setTabVal}>
          <ChipTabsList>
            <ChipTabsTrigger value="1" notification>추천소식</ChipTabsTrigger>
            <ChipTabsTrigger value="2">인기글</ChipTabsTrigger>
            <ChipTabsTrigger value="3">최신질문</ChipTabsTrigger>
          </ChipTabsList>
        </ChipTabsRoot>
      </div>
    </div>
  );
}

function ContentPlaceholderDemo() {
  const types = [
    { type: "default", label: "Default" },
    { type: "profile", label: "Profile" },
    { type: "coupon", label: "Coupon" },
    { type: "realty", label: "Realty" },
    { type: "car", label: "Car" },
    { type: "jobs", label: "Jobs" },
    { type: "buySell", label: "Buy-sell" },
    { type: "business", label: "Business" },
    { type: "post", label: "Post" },
    { type: "group", label: "Group" },
    { type: "image", label: "Image" },
    { type: "food", label: "Food" },
    { type: "commerce", label: "Commerce" },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x6)', width: '100%', maxWidth: 540, margin: '0 auto' }}>
      <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', textAlign: 'center' }}>
        SEED 2.0 Native Artwork Asset Presets (12 Types)
      </div>

      {/* Preset Types Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(95px, 1fr))', gap: 'var(--seed-dimension-x3)', justifyItems: 'center' }}>
        {types.map(({ type, label }) => (
          <div key={type} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 'var(--seed-dimension-x1_5)' }}>
            <ContentPlaceholder type={type} style={{ width: 90, height: 90, borderRadius: 'var(--seed-dimension-x3)' }} />
            <span style={{ fontSize: 'var(--seed-font-size-t1)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-subtle)', textAlign: 'center' }}>
              {label}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

function ContextualFloatingButtonDemo() {
  const [loading, setLoading] = useState(false);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x6)', width: '100%', maxWidth: 460, margin: '0 auto' }}>
      <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', textAlign: 'center' }}>
        Solid & Layer Tones · Float Composition · Loading State
      </div>

      {/* Mock Floating Frame */}
      <div style={{ position: 'relative', width: '100%', height: 200, backgroundColor: 'var(--seed-color-bg-neutral-weak)', borderRadius: 'var(--seed-dimension-x4)', border: '1px solid var(--seed-color-stroke-neutral-weak)', overflow: 'hidden', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center' }}>
        <div style={{ fontSize: 'var(--seed-font-size-t3)', color: 'var(--seed-color-fg-neutral-muted)', padding: 'var(--seed-dimension-x4)', textAlign: 'center' }}>
          콘텐츠 목록 영역 (하단 유동 배치 플로팅 팝업)
        </div>

        <Float placement="bottom-center" offsetY="x4">
          <ContextualFloatingButton variant="solid" loading={loading} onClick={() => { setLoading(true); setTimeout(() => setLoading(false), 2000); }}>
            <PrefixIcon svg={<IconBellFill />} />
            {loading ? "알림 설정 중..." : "알림 받기 설정"}
          </ContextualFloatingButton>
        </Float>
      </div>

      {/* Variant & Layout Grid */}
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--seed-dimension-x3)', justifyContent: 'center', alignItems: 'center' }}>
        <ContextualFloatingButton variant="solid">
          <PrefixIcon svg={<IconPlusLine />} />
          Solid Variant
        </ContextualFloatingButton>

        <ContextualFloatingButton variant="layer">
          <PrefixIcon svg={<IconPlusLine />} />
          Layer Variant
        </ContextualFloatingButton>

        <ContextualFloatingButton variant="layer" layout="iconOnly" aria-label="추가">
          <Icon svg={<IconPlusLine />} />
        </ContextualFloatingButton>
      </div>
    </div>
  );
}

function DatePickerDemo() {
  const [layoutMode, setLayoutMode] = useState("month");
  const today = { year: 2026, month: 8, day: 14 };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--seed-dimension-x6)', width: '100%', maxWidth: layoutMode === 'twoMonths' ? 720 : 420, margin: '0 auto', alignItems: 'center', transition: 'max-width 0.2s ease' }}>
      <div style={{ fontSize: 'var(--seed-font-size-t2)', fontWeight: 'var(--seed-font-weight-bold)', color: 'var(--seed-color-fg-neutral-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', textAlign: 'center' }}>
        Month · Two Months · Week · Continuous Layouts
      </div>

      {/* Mode Selector Buttons */}
      <div style={{ display: 'flex', gap: 'var(--seed-dimension-x2)', justifyContent: 'center', flexWrap: 'wrap' }}>
        <ActionButton
          variant={layoutMode === "month" ? "brandSolid" : "neutralOutline"}
          size="small"
          onClick={() => setLayoutMode("month")}
        >
          한 달 (Month)
        </ActionButton>
        <ActionButton
          variant={layoutMode === "week" ? "brandSolid" : "neutralOutline"}
          size="small"
          onClick={() => setLayoutMode("week")}
        >
          한 주 (Week)
        </ActionButton>
        <ActionButton
          variant={layoutMode === "twoMonths" ? "brandSolid" : "neutralOutline"}
          size="small"
          onClick={() => setLayoutMode("twoMonths")}
        >
          두 달 (Two Months)
        </ActionButton>
      </div>

      {/* Calendar Card Frame */}
      <div style={{ width: '100%', border: '1px solid var(--seed-color-stroke-neutral-weak)', borderRadius: 'var(--seed-dimension-x4)', padding: 'var(--seed-dimension-x4)', backgroundColor: 'var(--seed-color-bg-layer-default)', boxShadow: 'var(--seed-shadow-s1)', overflowX: 'auto' }}>
        {layoutMode === "month" && (
          <DatePicker today={today} defaultValue={today} />
        )}
        {layoutMode === "week" && (
          <WeekDatePicker today={today} defaultValue={today} />
        )}
        {layoutMode === "twoMonths" && (
          <div style={{ minWidth: 620 }}>
            <TwoMonthDatePicker today={today} defaultValue={today} />
          </div>
        )}
      </div>
    </div>
  );
}

const COMPONENTS = [
  {
    name: 'Accordion',
    slug: 'ui:accordion',
    demo: <AccordionDemo />,
  },

  {
    name: 'Action Button',
    slug: 'ui:action-button',
    demo: <ActionButtonDemo />,
  },

  {
    name: 'Alert Dialog',
    slug: 'ui:alert-dialog',
    demo: <AlertDialogDemo />,
  },

  {
    name: 'Attachment',
    slug: 'ui:attachment-field / ui:attachment-display-field',
    demo: <AttachmentDemo />,
  },

  {
    name: 'Avatar',
    slug: 'ui:avatar',
    demo: <AvatarDemo />,
  },

  {
    name: 'Badge',
    slug: 'ui:badge',
    demo: <BadgeDemo />,
  },

  {
    name: 'Bottom Navigation',
    slug: 'pattern:bottom-navigation',
    demo: <BottomNavigationDemo />,
  },

  {
    name: 'Bottom Sheet',
    slug: 'ui:bottom-sheet',
    demo: <BottomSheetDemo />,
  },

  {
    name: 'Callout',
    slug: 'ui:callout',
    demo: <CalloutDemo />,
  },

  {
    name: 'Checkbox',
    slug: 'ui:checkbox',
    demo: <CheckboxDemo />,
  },

  {
    name: 'Chip',
    slug: 'ui:chip / ui:chip-tabs',
    demo: <ChipDemo />,
  },

  {
    name: 'Content Placeholder',
    slug: 'ui:content-placeholder',
    demo: <ContentPlaceholderDemo />,
  },

  {
    name: 'Contextual Floating Button',
    slug: 'ui:contextual-floating-button',
    demo: <ContextualFloatingButtonDemo />,
  },

  {
    name: 'Date Picker',
    slug: 'ui:date-picker',
    demo: <DatePickerDemo />,
  },
];

export function ComponentGallery() {
  const [cur, setCur] = useState(0);
  const wrapRef = useRef(null);
  const navRef = useRef(null);
  const total = COMPONENTS.length;

  const go = (idx) => {
    if (idx < 0) idx = 0;
    if (idx >= total) idx = total - 1;
    setCur(idx);
  };

  useEffect(() => {
    if (wrapRef.current) {
      wrapRef.current.scrollTo({
        left: cur * wrapRef.current.clientWidth,
        behavior: 'smooth',
      });
    }
    if (navRef.current) {
      const activeBtn = navRef.current.children[cur];
      if (activeBtn) {
        activeBtn.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'center' });
      }
    }
  }, [cur]);

  return (
    <section className="comp-gallery-container" id="showcase">
      {/* 토글 네비 */}
      <div className="comp-nav" ref={navRef}>
        {COMPONENTS.map((c, i) => (
          <button
            key={c.name}
            className={`comp-nav-btn${i === cur ? ' active' : ''}`}
            onClick={() => go(i)}
          >
            {c.name}
          </button>
        ))}
      </div>

      {/* 상단 정보 바 (컴포넌트 이름/슬러그, dot 인디케이터, 이전/다음 화살표) */}
      <div className="comp-info-bar" style={{ marginBlock: 'var(--seed-dimension-x3_5)' }}>
        <div>
          <div className="comp-name">{COMPONENTS[cur].name}</div>
          <div className="comp-slug">{COMPONENTS[cur].slug}</div>
        </div>
        <div className="comp-dots" style={{ marginTop: 0 }}>
          {COMPONENTS.map((_, i) => (
            <button
              key={i}
              className={`comp-dot${i === cur ? ' active' : ''}`}
              onClick={() => go(i)}
              aria-label={COMPONENTS[i].name}
            />
          ))}
        </div>
        <div className="comp-arrows">
          <button className="comp-arrow-btn" onClick={() => go(cur - 1)} disabled={cur === 0}>‹</button>
          <button className="comp-arrow-btn" onClick={() => go(cur + 1)} disabled={cur === total - 1}>›</button>
        </div>
      </div>

      {/* 캐러셀 */}
      <div className="comp-carousel-wrap">
        <div className="comp-carousel-track" style={{ transform: `translateX(-${cur * 100}%)` }}>
          {COMPONENTS.map((c, i) => (
            <div key={c.name} className={`comp-carousel-slide${i === cur ? ' active' : ''}`}>
              {c.demo}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
